### ISSUE TITLE
Failed to run main_demo_13B.py

### ISSUE THREAD

**Issue by wegigabyteinsn** [PKU-YuanGroup/Chat-UniVi#30]
Traceback (most recent call last):
  File "/home/ubuntu22/anaconda3/envs/chatunivi/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu22/anaconda3/envs/chatunivi/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu22/anaconda3/envs/chatunivi/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu22/anaconda3/envs/chatunivi/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu22/anaconda3/envs/chatunivi/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/ubuntu22/anaconda3/envs/chatunivi/lib/python3.10/site-packages/uvicorn/main.py", line 409, in main
    run(
  File "/home/ubuntu22/anaconda3/envs/chatunivi/lib/python3.10/site-packages/uvicorn/main.py", line 575, in run
    server.run()
  File "/home/ubuntu22/anaconda3/envs/chatunivi/lib/python3.10/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/home/ubuntu22/anaconda3/envs/chatunivi/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/ubuntu22/anaconda3/envs/chatunivi/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/ubuntu22/anaconda3/envs/chatunivi/lib/python3.10/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/home/ubuntu22/anaconda3/envs/chatunivi/lib/python3.10/site-packages/uvicorn/server.py", line 76, in _serve
    config.load()
  File "/home/ubuntu22/anaconda3/envs/chatunivi/lib/python3.10/site-packages/uvicorn/config.py", line 433, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/ubuntu22/anaconda3/envs/chatunivi/lib/python3.10/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
  File "/home/ubuntu22/anaconda3/envs/chatunivi/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu22/chat/main_demo_13B.py", line 119, in <module>
    handler = Chat(model_path, conv_mode=conv_mode)
  File "/home/ubuntu22/chat/ChatUniVi/demo.py", line 16, in __init__
    self.tokenizer, self.model, self.image_processor, context_len = load_pretrained_model(model_path, None, model_name="ChatUniVi")
  File "/home/ubuntu22/chat/ChatUniVi/model/builder.py", line 75, in load_pretrained_model
    model = AutoModelForCausalLM.from_pretrained(model_path, low_cpu_mem_usage=True, **kwargs)
  File "/home/ubuntu22/anaconda3/envs/chatunivi/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 493, in from_pretrained
    return model_class.from_pretrained(
  File "/home/ubuntu22/anaconda3/envs/chatunivi/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2903, in from_pretrained
    ) = cls._load_pretrained_model(
  File "/home/ubuntu22/anaconda3/envs/chatunivi/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3002, in _load_pretrained_model
    raise ValueError(
ValueError: The current `device_map` had weights offloaded to the disk. Please provide an `offload_folder` for them. Alternatively, make sure you have `safetensors` installed if the model you are using offers the weights in this format.

**Comment by jpthu17** [comment]
This error is due to insufficient CPU RAM, specifically, the model parameters are loaded into CPU RAM before they are assigned to the GPUs. You can refer to the official documents: https://huggingface.co/blog/accelerate-large-models

![image](https://github.com/PKU-YuanGroup/Chat-UniVi/assets/53246557/25abab8e-1e7e-46cf-9e21-f52a43fbc0e2)

Please try to use the option ``` offload_folder="offload" ```.

**Comment by wegigabyteinsn** [comment]
> This error is due to insufficient CPU RAM, specifically, the model parameters are loaded into CPU RAM before they are assigned to the GPUs. You can refer to the official documents: https://huggingface.co/blog/accelerate-large-models
> 
> ![image](https://private-user-images.githubusercontent.com/53246557/321303822-25abab8e-1e7e-46cf-9e21-f52a43fbc0e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3NjUwMzgsIm5iZiI6MTcxMjc2NDczOCwicGF0aCI6Ii81MzI0NjU1Ny8zMjEzMDM4MjItMjVhYmFiOGUtMWU3ZS00NmNmLTllMjEtZjUyYTQzZmJjMGUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDE1NTg1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzZjZmOTg2YTEzMDRmNzE1MTFjM2YwZWFlMzkyYjYwYTUzYjY4MzYzNjk2ZThkYzNhYjI4MzFiMTk1Mjg4YmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ctxnF6nltgDroRUfIoYsTAAFAGni7_9EYShWKoLCpzE)
> 
> Please try to use the option `offload_folder="offload"`.

Loading checkpoint shards:  67%|███████████████████████████████████████████████████████████████████████████████████████████████████▎                                                 | 2/3 [00:18<00:09,  9.21s/it]Killed
